version: "3"
services:
  server:
    image: public.ecr.aws/l4e5z4f8/testlab/server
    container_name: "server"
    ports:
      - "3000:3000"
    environment:
      PG_HOST: database
    depends_on:
      - database
  database:
    image: public.ecr.aws/l4e5z4f8/testlab/postgres
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file:
      - .env
  frontend:
    image: public.ecr.aws/l4e5z4f8/testlab/admin-ui
    container_name: "admin-ui"
    ports:
      - "3001:3001"
    depends_on:
      - server
      - database
volumes:
  database-data:
